update

diff --git a/.github/workflows/build_copy.yml b/.github/workflows/build_copy.yml
--- a/.github/workflows/build_copy.yml
+++ b/.github/workflows/build_copy.yml
@@ -42,6 +42,8 @@ jobs:
 
     - name: Decrypt and install certificates and provisioning profiles
       run: |
+          set -x  # Enable debugging
+      
           echo ${{ secrets.DEV_P12_BASE64 }} | base64 --decode > AppCheckGit_Dev.p12
           echo ${{ secrets.DIS_P12_BASE64 }} | base64 --decode > AppCheckGit_Dis.p12
           echo ${{ secrets.DEV_MOBILEPROVISION_BASE64 }} | base64 --decode > AppCheckGit_Dev.mobileprovision
@@ -54,8 +56,8 @@ jobs:
           if [ ! -f AppCheckGit_Dis.mobileprovision ]; then echo "AppCheckGit_Dis.mobileprovision not created"; exit 1; fi
       
           security create-keychain -p "" build.keychain
-          security import AppCheckGit_Dev.p12 -k ~/Library/Keychains/build.keychain -P "intel123" -T /usr/bin/codesign
-          security import AppCheckGit_Dis.p12 -k ~/Library/Keychains/build.keychain -P "intel123" -T /usr/bin/codesign
+          security import AppCheckGit_Dev.p12 -k ~/Library/Keychains/build.keychain -P "intel123" -T /usr/bin/codesign || { echo "Failed to import AppCheckGit_Dev.p12"; exit 1; }
+          security import AppCheckGit_Dis.p12 -k ~/Library/Keychains/build.keychain -P "intel123" -T /usr/bin/codesign || { echo "Failed to import AppCheckGit_Dis.p12"; exit 1; }
       
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
           cp AppCheckGit_Dev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
@@ -65,6 +67,7 @@ jobs:
           security default-keychain -s ~/Library/Keychains/build.keychain
           security unlock-keychain -p "" ~/Library/Keychains/build.keychain
           security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain
+      
       
     # Step 6: Set up Ruby and install Fastlane
     - name: Set up Ruby and Install Fastlane
